### ISSUE TITLE
ROS2 Navigation Package Exploration

### ISSUE THREAD

**Issue by justincdavis** [Colorado-School-of-Mines-Robotics-Club/SpaceGrantEngine#26]

**Comment by HenryJohnson26** [comment]
https://navigation.ros.org/getting_started/index.html

**Comment by justincdavis** [comment]
https://navigation.ros.org/setup_guides/index.html

**Comment by justincdavis** [comment]
We can implement Navigation2 using our example test bed robot. I think this should be a critical task going forward. From what I can tell we can utilize our depthai-ros-driver that I merged to main to handle all nessecary data and then add one more node for "routing" the data between topics. 

Maybe on Sunday we can give this as a concrete task and see if we can get something working. Implementation of the model and everything should be done in this repo and then we can replicate to the repos for each robot when compelte.

**Comment by HenryJohnson26** [comment]
Can't make it to the meeting Sunday, wish you luck. would love to get caught up mon/tue
